
import {RentalFeature} from '../mocks/offers';
import {City} from '../mocks/offers';

export const allOffers = [
  {
    location: {
      city: City.PARIS,
      cityCoordinates: [48.85341, 2.3488],
    },
    offers: [
      {
        id: 0,
        coordinates: [48.84729076736546, 2.3435702650921173],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Beautiful & luxurious apartment at great location`,
        img: `/img/apartment-02.jpg`,
        imgDetails: [
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 120,
        rating: 3.4,
        type: `apartment`,
        isPremium: true,
        isBookmark: true,
        description: [
          `A bright and charming apartment with 1 bedroom, located close to Museum Square in one of the most cosmopolitan and vibrant districts of Amsterdam "de PIJP".`,
          `Perfect for short holidays, business trips.`,
        ],
        roomCountDetails: 3,
        maxGuestsDetails: 3,
        featuresDetails: [RentalFeature.DRYER, RentalFeature.WASHINGMACHINE],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2007-05-01`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2007-04-02`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 1,
        coordinates: [48.86105445652469, 2.353425297919433],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Wood and stone place`,
        img: `/img/apartment-02.jpg`,
        imgDetails: [
          `/img/apartment-02.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 80,
        rating: 4.1,
        type: `hotel`,
        isPremium: false,
        isBookmark: true,
        description: [
          `This package is special opportunity to connect accommodation in a traditional Dutch cottage located in a birch forest, taste the local food, and snowshoeing/hiking experience.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 2,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.CABLETV,
          RentalFeature.KITCHEN,
          RentalFeature.KITCHEN,
        ],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2020-05-06`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 1,
            name: `Mary`,
            avatar: `/img/avatar-angelina.jpg`,
            rating: 5,
            date: `2019-08-07`,
            text: `The building is in between the beach and metro station, 5 mins walking distance to both; 5 stops away from the Gothic Quarter by metro.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2004-05-02`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 2,
        coordinates: [48.851740683032126, 2.355683531887018],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Stylish and cozy place`,
        img: `/img/apartment-02.jpg`,
        imgDetails: [
          `/img/apartment-03.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 132,
        rating: 4.75,
        type: `house`,
        isPremium: true,
        isBookmark: false,
        description: [
          `Spacious apartment situated in the city centre (oud-West) of Amsterdam.`,
          `Walking distance to the Jordaan, Museum Quarter, Anne Frank house and Leidseplein.`,
          `Supermarket right on the corner.`,
        ],
        roomCountDetails: 4,
        maxGuestsDetails: 7,
        featuresDetails: [],
        reviews: [
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2006-08-09`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 3,
        coordinates: [48.84448831418782, 2.3495837700876474],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Excellent location and free parking`,
        img: `/img/apartment-02.jpg`,
        imgDetails: [
          `/img/room.jpg`,
          `/img/room-small.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 180,
        rating: 4.5,
        type: `apartmant`,
        isPremium: false,
        isBookmark: false,
        description: [
          `The studio apartments at Wittenberg have been carefully-designed to embrace and enhance the building’s timeless authentic features, whilst incorporating striking yet traditional Dutch interiors.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 4,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.PARKING,
        ],
        reviews: [],
      },
    ],
  },
  {
    location: {
      city: City.COLOGNE,
      cityCoordinates: [50.93333, 6.95],
    },
    offers: [
      {
        id: 0,
        coordinates: [50.93648019581346, 6.942350261681368],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Beautiful & luxurious apartment at great location`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 120,
        rating: 3.4,
        type: `apartmant`,
        isPremium: true,
        isBookmark: true,
        description: [
          `A bright and charming apartment with 1 bedroom, located close to Museum Square in one of the most cosmopolitan and vibrant districts of Amsterdam "de PIJP".`,
          `Perfect for short holidays, business trips.`,
        ],
        roomCountDetails: 3,
        maxGuestsDetails: 3,
        featuresDetails: [RentalFeature.DRYER, RentalFeature.WASHINGMACHINE],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2005-01-09`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2018-02-01`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 1,
        coordinates: [50.93813790167537, 6.944528103396974],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Wood and stone place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-02.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 80,
        rating: 4.1,
        type: `hotel`,
        isPremium: false,
        isBookmark: true,
        description: [
          `This package is special opportunity to connect accommodation in a traditional Dutch cottage located in a birch forest, taste the local food, and snowshoeing/hiking experience.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 2,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.CABLETV,
          RentalFeature.KITCHEN,
          RentalFeature.KITCHEN,
        ],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2007-07-07`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 1,
            name: `Mary`,
            avatar: `/img/avatar-angelina.jpg`,
            rating: 5,
            date: `2002-01-01`,
            text: `The building is in between the beach and metro station, 5 mins walking distance to both; 5 stops away from the Gothic Quarter by metro.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2020-01-07`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 2,
        coordinates: [50.93216655007104, 6.943741256017487],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Stylish and cozy place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-03.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 132,
        rating: 4.75,
        type: `house`,
        isPremium: true,
        isBookmark: false,
        description: [
          `Spacious apartment situated in the city centre (oud-West) of Amsterdam.`,
          `Walking distance to the Jordaan, Museum Quarter, Anne Frank house and Leidseplein.`,
          `Supermarket right on the corner.`,
        ],
        roomCountDetails: 4,
        maxGuestsDetails: 7,
        featuresDetails: [],
        reviews: [
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2015-03-03`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 3,
        coordinates: [50.9388574304378, 6.955421491548595],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Excellent location and free parking`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/room.jpg`,
          `/img/room-small.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 180,
        rating: 4.5,
        type: `apartmant`,
        isPremium: false,
        isBookmark: false,
        description: [
          `The studio apartments at Wittenberg have been carefully-designed to embrace and enhance the building’s timeless authentic features, whilst incorporating striking yet traditional Dutch interiors.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 4,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.PARKING,
        ],
        reviews: [],
      },
    ],
  },
  {
    location: {
      city: City.BRUSSELS,
      cityCoordinates: [50.85045, 4.34878],
    },
    offers: [
      {
        id: 0,
        coordinates: [50.83285722617625, 4.355064366628517],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Beautiful & luxurious apartment at great location`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 120,
        rating: 3.4,
        type: `apartment`,
        isPremium: true,
        isBookmark: true,
        description: [
          `A bright and charming apartment with 1 bedroom, located close to Museum Square in one of the most cosmopolitan and vibrant districts of Amsterdam "de PIJP".`,
          `Perfect for short holidays, business trips.`,
        ],
        roomCountDetails: 3,
        maxGuestsDetails: 3,
        featuresDetails: [RentalFeature.DRYER, RentalFeature.WASHINGMACHINE],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2020-04-04`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2005-05-08`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 1,
        coordinates: [50.855291836593814, 4.347456531940739],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Wood and stone place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-02.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 80,
        rating: 4.1,
        type: `hotel`,
        isPremium: false,
        isBookmark: true,
        description: [
          `This package is special opportunity to connect accommodation in a traditional Dutch cottage located in a birch forest, taste the local food, and snowshoeing/hiking experience.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 2,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.CABLETV,
          RentalFeature.KITCHEN,
          RentalFeature.KITCHEN,
        ],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2015-04-09`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 1,
            name: `Mary`,
            avatar: `/img/avatar-angelina.jpg`,
            rating: 5,
            date: `2016-06-05`,
            text: `The building is in between the beach and metro station, 5 mins walking distance to both; 5 stops away from the Gothic Quarter by metro.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2007-07-07`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 2,
        coordinates: [50.848518467982196, 4.350871923489649],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Stylish and cozy place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-03.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 132,
        rating: 4.75,
        type: `house`,
        isPremium: true,
        isBookmark: false,
        description: [
          `Spacious apartment situated in the city centre (oud-West) of Amsterdam.`,
          `Walking distance to the Jordaan, Museum Quarter, Anne Frank house and Leidseplein.`,
          `Supermarket right on the corner.`,
        ],
        roomCountDetails: 4,
        maxGuestsDetails: 7,
        featuresDetails: [],
        reviews: [
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2014-08-09`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 3,
        coordinates: [50.85889370871327, 4.34938756297568],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Excellent location and free parking`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/room.jpg`,
          `/img/room-small.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 180,
        rating: 4.5,
        type: `apartment`,
        isPremium: false,
        isBookmark: false,
        description: [
          `The studio apartments at Wittenberg have been carefully-designed to embrace and enhance the building’s timeless authentic features, whilst incorporating striking yet traditional Dutch interiors.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 4,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.PARKING,
        ],
        reviews: [],
      },
    ],
  },
  {
    location: {
      city: City.AMSTERDAM,
      cityCoordinates: [52.38333, 4.9],
    },
    offers: [
      {
        id: 0,
        coordinates: [52.3909553943508, 4.85309666406198],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Beautiful & luxurious apartment at great location`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 120,
        rating: 3.4,
        type: `apartment`,
        isPremium: true,
        isBookmark: true,
        description: [
          `A bright and charming apartment with 1 bedroom, located close to Museum Square in one of the most cosmopolitan and vibrant districts of Amsterdam "de PIJP".`,
          `Perfect for short holidays, business trips.`,
        ],
        roomCountDetails: 3,
        maxGuestsDetails: 3,
        featuresDetails: [RentalFeature.DRYER, RentalFeature.WASHINGMACHINE],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2013-03-07`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2017-07-07`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 1,
        coordinates: [52.369553943508, 4.85309666406198],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Wood and stone place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-02.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 80,
        rating: 4.1,
        type: `hotel`,
        isPremium: false,
        isBookmark: true,
        description: [
          `This package is special opportunity to connect accommodation in a traditional Dutch cottage located in a birch forest, taste the local food, and snowshoeing/hiking experience.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 2,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.CABLETV,
          RentalFeature.KITCHEN,
          RentalFeature.KITCHEN,
        ],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2020-09-09`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 1,
            name: `Mary`,
            avatar: `/img/avatar-angelina.jpg`,
            rating: 5,
            date: `2020-08-08`,
            text: `The building is in between the beach and metro station, 5 mins walking distance to both; 5 stops away from the Gothic Quarter by metro.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2016-09-05`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 2,
        coordinates: [52.3909553943508, 4.929309666406198],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Stylish and cozy place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-03.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 132,
        rating: 4.75,
        type: `house`,
        isPremium: true,
        isBookmark: false,
        description: [
          `Spacious apartment situated in the city centre (oud-West) of Amsterdam.`,
          `Walking distance to the Jordaan, Museum Quarter, Anne Frank house and Leidseplein.`,
          `Supermarket right on the corner.`,
        ],
        roomCountDetails: 4,
        maxGuestsDetails: 7,
        featuresDetails: [],
        reviews: [
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2014-06-05`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 3,
        coordinates: [52.3809553943508, 4.939309666406198],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Excellent location and free parking`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/room.jpg`,
          `/img/room-small.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 180,
        rating: 4.5,
        type: `apartment`,
        isPremium: false,
        isBookmark: false,
        description: [
          `The studio apartments at Wittenberg have been carefully-designed to embrace and enhance the building’s timeless authentic features, whilst incorporating striking yet traditional Dutch interiors.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 4,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.PARKING,
        ],
        reviews: [],
      },
    ],
  },
  {
    location: {
      city: City.HAMBURG,
      cityCoordinates: [53.57532, 10.01534],
    },
    offers: [
      {
        id: 0,
        coordinates: [53.5753005338843, 10.015979224991606],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Beautiful & luxurious apartment at great location`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 120,
        rating: 3.4,
        type: `apartment`,
        isPremium: true,
        isBookmark: true,
        description: [
          `A bright and charming apartment with 1 bedroom, located close to Museum Square in one of the most cosmopolitan and vibrant districts of Amsterdam "de PIJP".`,
          `Perfect for short holidays, business trips.`,
        ],
        roomCountDetails: 3,
        maxGuestsDetails: 3,
        featuresDetails: [RentalFeature.DRYER, RentalFeature.WASHINGMACHINE],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2012-09-08`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2020-03-02`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 1,
        coordinates: [53.578755238304936, 10.01224799128481],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Wood and stone place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-02.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 80,
        rating: 4.1,
        type: `hotel`,
        isPremium: false,
        isBookmark: true,
        description: [
          `This package is special opportunity to connect accommodation in a traditional Dutch cottage located in a birch forest, taste the local food, and snowshoeing/hiking experience.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 2,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.CABLETV,
          RentalFeature.KITCHEN,
          RentalFeature.KITCHEN,
        ],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2009-04-04`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 1,
            name: `Mary`,
            avatar: `/img/avatar-angelina.jpg`,
            rating: 5,
            date: `2007-05-07`,
            text: `The building is in between the beach and metro station, 5 mins walking distance to both; 5 stops away from the Gothic Quarter by metro.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2020-09-01`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 2,
        coordinates: [53.582470294110216, 10.01264598635923],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Stylish and cozy place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-03.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 132,
        rating: 4.75,
        type: `house`,
        isPremium: true,
        isBookmark: false,
        description: [
          `Spacious apartment situated in the city centre (oud-West) of Amsterdam.`,
          `Walking distance to the Jordaan, Museum Quarter, Anne Frank house and Leidseplein.`,
          `Supermarket right on the corner.`,
        ],
        roomCountDetails: 4,
        maxGuestsDetails: 7,
        featuresDetails: [],
        reviews: [
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2019-09-03`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 3,
        coordinates: [53.56668677413273, 10.01887378071594],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Excellent location and free parking`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/room.jpg`,
          `/img/room-small.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 180,
        rating: 4.5,
        type: `apartment`,
        isPremium: false,
        isBookmark: false,
        description: [
          `The studio apartments at Wittenberg have been carefully-designed to embrace and enhance the building’s timeless authentic features, whilst incorporating striking yet traditional Dutch interiors.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 4,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.PARKING,
        ],
        reviews: [],
      },
    ],
  },
  {
    location: {
      city: City.DUSSELDORF,
      cityCoordinates: [51.22172, 6.77616],
    },
    offers: [
      {
        id: 0,
        coordinates: [51.225446719407095, 6.770537831659981],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Beautiful & luxurious apartment at great location`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 120,
        rating: 3.4,
        type: `apartment`,
        isPremium: true,
        isBookmark: true,
        description: [
          `A bright and charming apartment with 1 bedroom, located close to Museum Square in one of the most cosmopolitan and vibrant districts of Amsterdam "de PIJP".`,
          `Perfect for short holidays, business trips.`,
        ],
        roomCountDetails: 3,
        maxGuestsDetails: 3,
        featuresDetails: [RentalFeature.DRYER, RentalFeature.WASHINGMACHINE],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2020-09-07`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2000-05-01`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 1,
        coordinates: [51.222726767966954, 6.780774794092512],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Wood and stone place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-02.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 80,
        rating: 4.1,
        type: `hotel`,
        isPremium: false,
        isBookmark: true,
        description: [
          `This package is special opportunity to connect accommodation in a traditional Dutch cottage located in a birch forest, taste the local food, and snowshoeing/hiking experience.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 2,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.CABLETV,
          RentalFeature.KITCHEN,
          RentalFeature.KITCHEN,
        ],
        reviews: [
          {
            id: 0,
            name: `Adam`,
            avatar: `/img/avatar-max.jpg`,
            rating: 4,
            date: `2017-09-02`,
            text: `Easy Check In: Management did extra mile, and allowed me to check in several hours before. Cleaning of my unit was swiftly organized, and properly introduced.`,
          },
          {
            id: 1,
            name: `Mary`,
            avatar: `/img/avatar-angelina.jpg`,
            rating: 5,
            date: `2020-04-04`,
            text: `The building is in between the beach and metro station, 5 mins walking distance to both; 5 stops away from the Gothic Quarter by metro.`,
          },
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2020-01-01`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 2,
        coordinates: [51.213949205873114, 6.780531756137994],
        host: {
          hostName: `Angelina`,
          photo: `/img/avatar-angelina.jpg`,
          isSuper: true,
        },
        name: `Stylish and cozy place`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/apartment-03.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 132,
        rating: 4.75,
        type: `house`,
        isPremium: true,
        isBookmark: false,
        description: [
          `Spacious apartment situated in the city centre (oud-West) of Amsterdam.`,
          `Walking distance to the Jordaan, Museum Quarter, Anne Frank house and Leidseplein.`,
          `Supermarket right on the corner.`,
        ],
        roomCountDetails: 4,
        maxGuestsDetails: 7,
        featuresDetails: [],
        reviews: [
          {
            id: 2,
            name: `Alex`,
            avatar: `/img/avatar.svg`,
            rating: 5,
            date: `2018-08-08`,
            text: `We need a quick place to stay for the night and rented the same day. Was nice and clean. Had parking available for 15€ for the night. Was a little noisy but it ended by 11pm and we were able to get a decent night sleep. Had everything we needed.`,
          },
        ],
      },
      {
        id: 3,
        coordinates: [51.21624789556441, 6.780427787972119],
        host: {
          hostName: `Max`,
          photo: `/img/avatar-max.jpg`,
          isSuper: false,
        },
        name: `Excellent location and free parking`,
        img: `/img/apartment-01.jpg`,
        imgDetails: [
          `/img/room.jpg`,
          `/img/room-small.jpg`,
          `/img/apartment-01.jpg`,
          `/img/apartment-02.jpg`,
          `/img/apartment-03.jpg`,
          `/img/apartment-small-03.jpg`,
          `/img/apartment-small-04.jpg`,
        ],
        price: 180,
        rating: 4.5,
        type: `apartment`,
        isPremium: false,
        isBookmark: false,
        description: [
          `The studio apartments at Wittenberg have been carefully-designed to embrace and enhance the building’s timeless authentic features, whilst incorporating striking yet traditional Dutch interiors.`,
        ],
        roomCountDetails: 2,
        maxGuestsDetails: 4,
        featuresDetails: [
          RentalFeature.DRYER,
          RentalFeature.WASHINGMACHINE,
          RentalFeature.PARKING,
        ],
        reviews: [],
      },
    ],
  },
];
